name: Deploy-Android-TEST 

on:
  push:
    branches:
      - '**'
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID_TEST }}  
  APP_NAME: ${{ 'MyApp-Android/ENV_TEST'  }}  
  TESTING_GROUP: ${{  'ENV_TEST'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }}  
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build android
        run:  cd android && ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
