name: Deploy-Android-TEST 

on:
  push:
    branches:
      - '**'
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID_TEST }}  
  APP_NAME: ${{ 'My_Own_Apps/ENV_TEST'  }}  
  TESTING_GROUP: ${{  'ENV_TEST'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/release/app-release.apk'  }}  
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        
      - name: Generate App APK
        run: cd android && ./gradlew assembleRelease --no-daemon

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
